import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        tertiary: "#000f1e",
        error: "#ba1a1a",
        "tertiary-fixed": "#cfe5fe",
        "surface-bright": "#fdf9ee",
        "on-error": "#ffffff",
        "on-primary-fixed": "#0e1b32",
        "secondary-fixed-dim": "#f5bc6c",
        outline: "#75777e",
        background: "#fdf9ee",
        primary: "#010d23",
        "error-container": "#ffdad6",
        "surface-container-high": "#ece8dd",
        "on-primary-container": "#7e8aa6",
        "on-secondary-fixed": "#291800",
        "surface-tint": "#525f78",
        "on-tertiary-fixed-variant": "#34495d",
        "on-tertiary-container": "#788da4",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f7f3e8",
        "inverse-surface": "#323129",
        "surface-container": "#f2eee3",
        secondary: "#80560b",
        "surface-container-highest": "#e6e2d7",
        "secondary-fixed": "#ffddb3",
        "inverse-on-surface": "#f5f0e5",
        "surface-variant": "#e6e2d7",
        "primary-fixed": "#d7e2ff",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#3a4760",
        "on-secondary-container": "#794f03",
        "primary-fixed-dim": "#bac7e5",
        "on-secondary-fixed-variant": "#624000",
        "surface-dim": "#dedacf",
        "on-surface-variant": "#45474d",
        "on-tertiary-fixed": "#061d30",
        "outline-variant": "#c5c6ce",
        "on-surface": "#1c1c15",
        "primary-container": "#16233a",
        "tertiary-container": "#0f2538",
        "on-primary": "#ffffff",
        "inverse-primary": "#bac7e5",
        "on-background": "#1c1c15",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#ffc573",
        surface: "#fdf9ee",
        "tertiary-fixed-dim": "#b4c9e2",
        "duty-red": "#C0392B",
        "ink-navy": "#16233A",
        "manifest-paper": "#F0ECE1",
        "steel-blue": "#525f78",
        brass: "#f5bc6c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "32px",
        "stack-sm": "8px",
        "stack-md": "16px",
        gutter: "24px",
        unit: "4px",
        "margin-page": "48px",
      },
      fontFamily: {
        "display-lg": ['"Source Serif 4"', "serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg": ['"Source Serif 4"', "serif"],
        "title-md": ['"Source Serif 4"', "serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "code-sm": ["14px", { lineHeight: "1.5", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
