"""
Unit tests for SQLAlchemy models.

Tests cover:
- Model instantiation with defaults
- UUID auto-generation
- Nullable field behavior
- JSON field serialization (stacks_with, mutually_exclusive_with)
"""

import pytest
from datetime import date

from app.models import HTSCode, TariffRule, Exclusion, FXRate, CalculationLog


class TestHTSCodeModel:
    """Test HTSCode model."""

    def test_create_with_required_fields(self):
        hts = HTSCode(code="99", level="chapter", description="Test chapter")
        assert hts.code == "99"
        assert hts.level == "chapter"
        assert hts.parent_code is None

    def test_uuid_auto_generated(self):
        """UUID is auto-generated on flush/insert, not on Python instantiation."""
        hts = HTSCode(code="99", level="chapter", description="Test")
        # Before flush, id is None (generated by DB insert default)
        # After adding to session and flushing, id would be set
        # For unit test without DB, verify the default callable exists
        from app.models.hts_code import HTSCode as Model
        id_col = Model.__table__.columns["id"]
        assert id_col.default is not None


class TestTariffRuleModel:
    """Test TariffRule model."""

    def test_create_with_all_fields(self):
        rule = TariffRule(
            tariff_type="SECTION_301",
            hts_code_pattern="8483",
            origin_country="CN",
            rate=0.25,
            effective_from=date(2018, 7, 6),
            effective_to=None,
            stacks_with=["MFN"],
            mutually_exclusive_with=["IEEPA"],
            description="Test rule",
            source_reference="Test ref",
        )
        assert rule.tariff_type == "SECTION_301"
        assert rule.rate == 0.25
        assert rule.stacks_with == ["MFN"]
        assert rule.mutually_exclusive_with == ["IEEPA"]
        assert rule.effective_to is None

    def test_json_fields_default_to_empty_list(self):
        rule = TariffRule(
            tariff_type="MFN",
            hts_code_pattern="84",
            origin_country="CN",
            rate=0.02,
            effective_from=date(2000, 1, 1),
        )
        # JSON fields should have default empty lists
        assert rule.stacks_with == [] or rule.stacks_with is None
        assert rule.mutually_exclusive_with == [] or rule.mutually_exclusive_with is None


class TestExclusionModel:
    """Test Exclusion model."""

    def test_create_indefinite_exclusion(self):
        exc = Exclusion(
            hts_code="8542.31",
            tariff_type="IEEPA",
            origin_country="CN",
            effective_from=date(2025, 4, 9),
            effective_to=None,
            description="Permanent exclusion",
        )
        assert exc.effective_to is None
        assert exc.hts_code == "8542.31"

    def test_create_temporary_exclusion(self):
        exc = Exclusion(
            hts_code="8517.12",
            tariff_type="SECTION_301",
            origin_country="CN",
            effective_from=date(2025, 4, 11),
            effective_to=date(2025, 7, 9),
            description="Temporary exclusion",
        )
        assert exc.effective_to == date(2025, 7, 9)


class TestFXRateModel:
    """Test FXRate model."""

    def test_create_rate(self):
        rate = FXRate(
            from_currency="CNY",
            to_currency="USD",
            rate=0.1389,
            date=date(2026, 8, 1),
        )
        assert rate.from_currency == "CNY"
        assert rate.to_currency == "USD"
        assert rate.rate == 0.1389


class TestCalculationLogModel:
    """Test CalculationLog model."""

    def test_create_log(self):
        log = CalculationLog(
            hts_code="8483.40",
            import_date=date(2026, 8, 1),
            origin_country="CN",
            input_data={"hts_code": "8483.40", "invoice_value_usd": 5000},
            matched_rules=["mfn-8483", "301-8483"],
            exclusions_applied=[],
            result_data={"landed_cost_usd": 6500},
        )
        assert log.hts_code == "8483.40"
        assert log.matched_rules == ["mfn-8483", "301-8483"]
        assert log.exclusions_applied == []
        assert log.result_data["landed_cost_usd"] == 6500
