/**
 * PDF Export — Professional "Entry Summary" document
 * styled like an official CBP Form 7501.
 *
 * Layout:
 * ┌─────────────────────────────────────────┐
 * │ [Red accent bar]                        │
 * │ LANDED COST LEDGER — ENTRY SUMMARY      │
 * │ Ref: calc_id  │  Date: ...  │  Page 1/1 │
 * ├─────────────────────────────────────────┤
 * │ SHIPMENT DETAILS                        │
 * │ HTS: ...  Origin: ...  Import: ...      │
 * ├─────────────────────────────────────────┤
 * │ VALUATION                               │
 * │ Invoice Value .................. $X,XXX  │
 * │ Freight ........................ $X,XXX  │
 * │ Insurance ...................... $X,XXX  │
 * │ ─────────────────────────────────────── │
 * │ Customs Value (CIF) ........... $X,XXX  │
 * ├─────────────────────────────────────────┤
 * │ DUTY ASSESSMENT                         │
 * │ ┌──────────┬───────┬─────────┬───────┐ │
 * │ │ Type     │ Rate  │ Amount  │Status │ │
 * │ └──────────┴───────┴─────────┴───────┘ │
 * ├─────────────────────────────────────────┤
 * │ TOTAL LANDED COST          $XX,XXX.XX   │
 * ├─────────────────────────────────────────┤
 * │ Notes / Disclaimer                      │
 * └─────────────────────────────────────────┘
 */

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { CalculationResult } from "./types";
import type { Locale } from "./i18n";

// Brand colors
const NAVY = [22, 35, 58] as const;      // #16233A
const RED = [192, 57, 43] as const;       // #C0392B
const BRASS = [245, 188, 108] as const;   // #F5BC6C
const GRAY = [69, 71, 77] as const;       // #45474D
const LIGHT_GRAY = [240, 236, 225] as const; // #F0ECE1

// =============================================================================
// PDF Labels — bilingual
// =============================================================================

const PDF_LABELS: Record<Locale, Record<string, string>> = {
  en: {
    title: "LANDED COST LEDGER",
    subtitle: "ENTRY SUMMARY — DUTY ASSESSMENT",
    page: "Page 1/1",
    ref: "Ref",
    date: "Date",
    shipment: "SHIPMENT DETAILS",
    hts_code: "HTS CODE",
    origin: "COUNTRY OF ORIGIN",
    import_date: "DATE OF IMPORT",
    de_minimis_title: "DE MINIMIS THRESHOLD APPLIED",
    de_minimis_desc: "is under $800 — no duties or fees apply.",
    valuation: "VALUATION",
    invoice_value: "Commercial Invoice Value",
    freight: "+ Freight & Insurance",
    customs_value: "Customs Value (CIF)",
    duty_assessment: "DUTY ASSESSMENT",
    col_type: "Tariff / Fee Type",
    col_rate: "Rate",
    col_amount: "Amount (USD)",
    col_status: "Status",
    applied: "APPLIED",
    not_applied: "NOT APPLIED",
    total_duties: "Total Duties:",
    total_fees: "Fees (MPF + HMF):",
    total_landed: "TOTAL LANDED COST",
    notes: "NOTES",
    fta_note: "Free Trade Agreement: {fta} — MFN duty exempted for qualifying goods.",
    fx_note: "Exchange Rate: 1 {from} = {rate} {to} (date: {date}, source: {source})",
    disclaimer_1: "DISCLAIMER: This document is generated by Landed Cost Ledger for estimation purposes only.",
    disclaimer_2: "It does not constitute legal or customs brokerage advice. Consult a licensed customs broker for official CBP filings.",
    disclaimer_3: "Rates are based on available data and may not reflect the latest Federal Register amendments.",
  },
  th: {
    title: "ระบบคำนวณต้นทุนนำเข้า",
    subtitle: "ใบสรุปการประเมินภาษีนำเข้า",
    page: "หน้า 1/1",
    ref: "เลขอ้างอิง",
    date: "วันที่",
    shipment: "รายละเอียดการนำเข้า",
    hts_code: "รหัส HTS",
    origin: "ประเทศต้นทาง",
    import_date: "วันที่นำเข้า",
    de_minimis_title: "ยกเว้นภาษี (DE MINIMIS)",
    de_minimis_desc: "ต่ำกว่า $800 — ไม่เสียภาษีและค่าธรรมเนียม",
    valuation: "การประเมินมูลค่า",
    invoice_value: "มูลค่าตามใบกำกับสินค้า",
    freight: "+ ค่าขนส่งและประกัน",
    customs_value: "มูลค่าศุลกากร (CIF)",
    duty_assessment: "การประเมินภาษี",
    col_type: "ประเภทภาษี/ค่าธรรมเนียม",
    col_rate: "อัตรา",
    col_amount: "จำนวนเงิน (USD)",
    col_status: "สถานะ",
    applied: "เก็บภาษี",
    not_applied: "ไม่เก็บ",
    total_duties: "ภาษีรวม:",
    total_fees: "ค่าธรรมเนียม (MPF + HMF):",
    total_landed: "ต้นทุนนำเข้ารวมทั้งหมด",
    notes: "หมายเหตุ",
    fta_note: "ข้อตกลงการค้าเสรี: {fta} — ยกเว้นภาษี MFN สำหรับสินค้าที่เข้าเงื่อนไข",
    fx_note: "อัตราแลกเปลี่ยน: 1 {from} = {rate} {to} (วันที่: {date}, แหล่ง: {source})",
    disclaimer_1: "หมายเหตุ: เอกสารนี้จัดทำโดยระบบ Landed Cost Ledger เพื่อการประมาณการเท่านั้น",
    disclaimer_2: "ไม่ถือเป็นคำแนะนำทางกฎหมายหรือศุลกากร กรุณาปรึกษาตัวแทนออกของ (Customs Broker) สำหรับการยื่นเอกสารจริง",
    disclaimer_3: "อัตราภาษีอ้างอิงจากข้อมูลที่มี อาจไม่สะท้อนการแก้ไขล่าสุดจาก Federal Register",
  },
};

export function exportCalculationPDF(result: CalculationResult, locale: Locale = "en") {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;
  const L = PDF_LABELS[locale];

  const fmt = (n: number) => `$${n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

  // ─────────────────────────────────────────────────────────────────────────
  // RED ACCENT BAR (top)
  // ─────────────────────────────────────────────────────────────────────────
  doc.setFillColor(...RED);
  doc.rect(0, 0, pageWidth, 4, "F");
  y = 4;

  // ─────────────────────────────────────────────────────────────────────────
  // HEADER SECTION
  // ─────────────────────────────────────────────────────────────────────────
  doc.setFillColor(...NAVY);
  doc.rect(0, y, pageWidth, 28, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text(L.title, margin, y + 12);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...BRASS);
  doc.text(L.subtitle, margin, y + 20);

  // Right side: reference info
  doc.setFontSize(8);
  doc.setTextColor(200, 200, 200);
  doc.text(`${L.ref}: ${result.calculation_id.slice(0, 8).toUpperCase()}`, pageWidth - margin, y + 10, { align: "right" });
  doc.text(`${L.date}: ${new Date().toISOString().split("T")[0]}`, pageWidth - margin, y + 16, { align: "right" });
  doc.text(L.page, pageWidth - margin, y + 22, { align: "right" });

  y += 32;

  // ─────────────────────────────────────────────────────────────────────────
  // SHIPMENT DETAILS
  // ─────────────────────────────────────────────────────────────────────────
  doc.setFillColor(...LIGHT_GRAY);
  doc.rect(margin, y, contentWidth, 20, "F");
  doc.setDrawColor(200, 200, 200);
  doc.rect(margin, y, contentWidth, 20, "S");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text(L.shipment, margin + 4, y + 6);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(0);

  const col1 = margin + 4;
  const col2 = margin + 65;
  const col3 = margin + 120;
  const detailY = y + 14;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...GRAY);
  doc.text(L.hts_code, col1, detailY - 3);
  doc.text(L.origin, col2, detailY - 3);
  doc.text(L.import_date, col3, detailY - 3);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.text(result.hts_code, col1, detailY + 3);
  doc.setFontSize(10);
  doc.text(result.origin_country, col2, detailY + 3);
  doc.text(result.import_date, col3, detailY + 3);

  y += 26;

  // ─────────────────────────────────────────────────────────────────────────
  // DE MINIMIS CHECK
  // ─────────────────────────────────────────────────────────────────────────
  if (result.de_minimis_applied) {
    doc.setFillColor(220, 255, 220);
    doc.rect(margin, y, contentWidth, 20, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(34, 120, 34);
    doc.text(L.de_minimis_title, margin + 4, y + 9);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`${fmt(result.customs_value_usd)} ${L.de_minimis_desc}`, margin + 4, y + 16);
    y += 26;
    addFooter(doc, margin, pageWidth, L);
    doc.save(`entry-summary-${result.hts_code}-${result.import_date}.pdf`);
    return;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // VALUATION TABLE
  // ─────────────────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text(L.valuation, margin + 4, y + 5);
  y += 8;

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [["Description", L.col_amount]],
    body: [
      [L.invoice_value, fmt(result.invoice_value_usd)],
      [L.freight, fmt(result.customs_value_usd - result.invoice_value_usd > 0 ? result.customs_value_usd - result.invoice_value_usd : 0)],
      [{ content: L.customs_value, styles: { fontStyle: "bold" } }, { content: fmt(result.customs_value_usd), styles: { fontStyle: "bold" } }],
    ],
    theme: "plain",
    headStyles: { fillColor: NAVY as any, textColor: 255, fontSize: 8, fontStyle: "bold", cellPadding: 4 },
    bodyStyles: { fontSize: 9, cellPadding: 3, textColor: [30, 30, 30] },
    alternateRowStyles: { fillColor: [250, 248, 243] },
    columnStyles: { 1: { halign: "right" } },
  });

  y = (doc as any).lastAutoTable.finalY + 6;

  // ─────────────────────────────────────────────────────────────────────────
  // DUTY ASSESSMENT TABLE
  // ─────────────────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text(L.duty_assessment, margin + 4, y + 5);
  y += 8;

  const dutyRows = result.tariff_breakdown.map((item) => {
    const status = item.applied ? L.applied : (item.reason ?? L.not_applied);
    return [
      item.type.replace("_", " "),
      item.rate != null ? `${(item.rate * 100).toFixed(3)}%` : "—",
      item.applied ? fmt(item.amount_usd ?? 0) : "—",
      status,
    ];
  });

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [[L.col_type, L.col_rate, L.col_amount, L.col_status]],
    body: dutyRows,
    theme: "grid",
    headStyles: { fillColor: RED as any, textColor: 255, fontSize: 8, fontStyle: "bold", cellPadding: 4 },
    bodyStyles: { fontSize: 8, cellPadding: 3 },
    alternateRowStyles: { fillColor: [255, 250, 248] },
    columnStyles: {
      1: { halign: "center" },
      2: { halign: "right" },
      3: { halign: "center", fontStyle: "italic", textColor: [100, 100, 100], fontSize: 7 },
    },
    didParseCell: (data: any) => {
      // Highlight applied rows
      if (data.section === "body" && data.column.index === 3) {
        const val = data.cell.raw;
        if (val === L.applied) {
          data.cell.styles.textColor = [34, 120, 34];
          data.cell.styles.fontStyle = "bold";
        } else {
          data.cell.styles.textColor = [150, 150, 150];
        }
      }
    },
  });

  y = (doc as any).lastAutoTable.finalY + 8;

  // ─────────────────────────────────────────────────────────────────────────
  // TOTALS SECTION
  // ─────────────────────────────────────────────────────────────────────────
  // Double line
  doc.setDrawColor(...NAVY);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  doc.line(margin, y + 1.5, pageWidth - margin, y + 1.5);
  y += 6;

  // Subtotals
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);

  doc.text(L.total_duties, margin + 4, y + 5);
  doc.text(fmt(result.total_duty_usd), pageWidth - margin - 4, y + 5, { align: "right" });
  y += 8;

  if (result.fees) {
    doc.text(L.total_fees, margin + 4, y + 5);
    doc.text(fmt(result.fees.total_fees_usd), pageWidth - margin - 4, y + 5, { align: "right" });
    y += 8;
  }

  // Grand total box
  y += 4;
  doc.setFillColor(...NAVY);
  doc.roundedRect(margin, y, contentWidth, 18, 2, 2, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text(L.total_landed, margin + 6, y + 11);

  doc.setFontSize(14);
  doc.text(fmt(result.landed_cost_usd), pageWidth - margin - 6, y + 12, { align: "right" });

  y += 26;

  // ─────────────────────────────────────────────────────────────────────────
  // FTA / FX NOTES
  // ─────────────────────────────────────────────────────────────────────────
  if (result.fta_applied || result.fx_rate_used) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.text(L.notes, margin + 4, y + 4);
    y += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);

    if (result.fta_applied) {
      doc.text(L.fta_note.replace("{fta}", result.fta_applied), margin + 4, y + 4);
      y += 6;
    }

    if (result.fx_rate_used) {
      const fxText = L.fx_note
        .replace("{from}", result.fx_rate_used.from_currency)
        .replace("{rate}", String(result.fx_rate_used.rate))
        .replace("{to}", result.fx_rate_used.to_currency)
        .replace("{date}", result.fx_rate_used.date)
        .replace("{source}", (result.fx_rate_used as any).source ?? "database");
      doc.text(fxText, margin + 4, y + 4);
      y += 6;
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // FOOTER
  // ─────────────────────────────────────────────────────────────────────────
  addFooter(doc, margin, pageWidth, L);

  // Save
  doc.save(`entry-summary-${result.hts_code}-${result.import_date}.pdf`);
}

function addFooter(doc: jsPDF, margin: number, pageWidth: number, L: Record<string, string>) {
  const footerY = 280;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.2);
  doc.line(margin, footerY - 4, pageWidth - margin, footerY - 4);

  doc.setFont("helvetica", "italic");
  doc.setFontSize(6.5);
  doc.setTextColor(140, 140, 140);
  doc.text(L.disclaimer_1, margin, footerY);
  doc.text(L.disclaimer_2, margin, footerY + 4);
  doc.text(L.disclaimer_3, margin, footerY + 8);
}
